image: "openjdk:11-jre-slim"


before_script:
  - apt-get update -qy
  - apt-get install -y --no-install-recommends apt-transport-https apt-utils bc dirmngr gnupg
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - echo "dash hold" | dpkg --set-selections
  - apt-get update -qy
  - apt-get upgrade -y
  - apt-get install -y --no-install-recommends sbt
  - apt-get install git -y
  - apt-get install wget -
  - cd ~
  - echo $JAVA_HOME
  - wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java8-linux-amd64-19.3.1.tar.gz
  - tar -xf graalvm-ce-java8-linux-amd64-19.3.1.tar.gz
  - git clone --single-branch --branch develop https://github.com/aslesarenko/ergo-appkit.git
  - cd ergo-appkit
  - git checkout 60478389921a2aabe4d79f223f54a6bd12a09e4c
  - rm -rf target 2> /dev/null
  - export PATH=/root/graalvm-ce-java8-19.3.1/bin:$PATH
  - sbt publishLocal


stages:
  - test

test:
  stage: test
  script:
  - sbt clean coverage test coverageReport
